### DISCUSSION TITLE
Configuration: Example config.yaml? Can I include both `exclude_checks` and `explicit_checks`?

### DISCUSSION THREAD

**Discussion by arrowtype** [fonttools/fontbakery#4588] [Q&A]
My basic goal is to run the universal profile, with a few useful googlefonts checks added in, and have it create a single ghmarkdown file of check results.

So, I’m trying to use the `check-universal` profile with an `--configuration` argument pointing to a YAML file, but I’m having issues.

I have a config.yaml file that looks like this:

```yaml
---
exclude_checks:
  - com.google.fonts/check/alt_caron
  - com.google.fonts/check/contour_count
  - com.google.fonts/check/math_signs_width
explicit_checks:
  - com.google.fonts/check/name/ascii_only_entries
  - com.google.fonts/check/fstype
  - com.google.fonts/check/name/unwanted_chars
  - com.google.fonts/check/usweightclass
  - com.google.fonts/check/integer_ppem_if_hinted
  - com.google.fonts/check/os2/use_typo_metrics
  - com.google.fonts/check/meta/script_lang_tags
```

And I’m running it like this:

```sh
fontbakery check-universal "fontfamily.ttf" --configuration "fontbakery-config.yaml"
```

However, I can only get that to work with the `check-universal` profile if I _only_ have the `exclude_checks` list. If I include both lists, it seems to run zero checks.

Or, I can get it to work with the `check-googlefonts` profile, but then it is _only_ checking the few explicit checks. 

My goal is to: 
- Run almost all the checks in the universal profile, except for a few that don’t make sense for a current family.
- Add in a few useful checks from other profiles.

So, a couple of questions:
1. Am I using the right approach, or should I be doing something else?
2. Is there an example `config.yaml` file somewhere? So far, I have only found an example of a Python config list in the docs, and some very basic yaml in the code tests. It might be helpful if there were a moderately complex config.yaml example that I could reference.
3. Can I pull in googlefonts checks if I’m running `checks-universal`?

Thanks so much for any insights!
