### ISSUE TITLE
Running TN profile from GitHub action not working

### ISSUE THREAD

**Issue by eweracs** [fonttools/fontbakery#4620]
## Observed behaviour

I am trying to run the TN profile from a GitHub action. The universal profile works fine. However, when I try to run the TN profile, I get the following:

```
Start ... running 518 individual check executions.

To run the typenetwork profile, one needs to install
fontbakery with the 'typenetwork' extra, like this:

python -m pip install -U 'fontbakery[typenetwork]'

```

I have the installation line set up as `python -m pip install -U 'fontbakery[typenetwork]'`, but I get the same result.

## Expected behaviour

I would expect the TN profile to work following the instructions provided. It works fine from my local Terminal.

## Resources and steps needed to reproduce

Try running FB through a GitHub action with the TN profile.

**Comment by felipesanches** [comment]
I was not able to replicate this behaviour with the latest git revision. But after some inspection, I found out that this only happens on revisions older than March 18, 2024, when @simoncozens committed a change with this log-message:

![Screenshot from 2024-03-30 17-29-41](https://github.com/fonttools/fontbakery/assets/213676/6dc1039e-f062-4c5c-b5d8-689233f3f292)


It means you're trying to run it from an old revision. You need to update your local copy of the git repo by running these commands:

 > git fetch origin
 > git rebase origin/main

**note:** Here I am assuming that **origin** is a git-remote pointing to https://github.com/fonttools/fontbakery.git which is the usual state of git after a simple git-clone, which is what I guess you did a couple weeks ago or a bit before that.

**Comment by felipesanches** [comment]
oh! Now I have re-read your original message and noticed that "from GitHub" does not mean you're running from git repo.

So, my suggestion is that you change the install procedures to do this:

 > python -m pip install --pre -U 'fontbakery[typenetwork]'

By using the **--pre** flag, it will install the pre-releases, which are updated more frequently and at this moment already include the commit that fixed this problem.

**Comment by eweracs** [comment]
Great, thanks, I will give that a try.

**Comment by eweracs** [comment]
Hello, I tried with the --pre flag, but now I get the following the running with the TN profile:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.2/x64/bin/fontbakery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/fontbakery/cli.py", line 423, in main
    profile = profile_factory(get_module(args.profile))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/fontbakery/fonts_profile.py", line 150, in profile_factory
    add_checks_to_nascent_profile(
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/fontbakery/fonts_profile.py", line 1[16](https://github.com/mnkytype/ella/actions/runs/8499420275/job/23280223641#step:6:17), in add_checks_to_nascent_profile
    raise ValueError(f"Check {check} not found")
ValueError: Check com.google.fonts/check/family/panose_proportion not found
```

**Comment by guidoferreyra** [comment]
Not sure why is complaining about ´com.google.fonts/check/family/panose_proportion´ TN profile doesn’t use it since it was deprecated some time ago.

**Comment by eweracs** [comment]
Does running FB with the TN profile through a GitHub action work for you? My basic structure is this:

```
name: QA, build fonts, zip up

on:
  workflow_call:

jobs:
  fontbakery-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Fontbakery
      run: |
        python -m pip install --pre -U 'fontbakery[typenetwork]'

    - name: Run Fontbakery Check
      run: |        
        fontbakery check-typenetwork -F --html "CFF_report.html" "*.otf" || true
```
